// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
)

type Assignedproject struct {
	UserID    int32        `json:"user_id"`
	ProjectID int32        `json:"project_id"`
	Issued    sql.NullBool `json:"issued"`
}

type Project struct {
	ID          int32          `json:"id"`
	Title       sql.NullString `json:"title"`
	Description sql.NullString `json:"description"`
	TotalAmount sql.NullString `json:"total_amount"`
	OrderDate   sql.NullTime   `json:"order_date"`
	Status      sql.NullBool   `json:"status"`
	UserID      int32          `json:"user_id"`
	Fee         sql.NullString `json:"fee"`
}

type Projectcomment struct {
	ID        int32          `json:"id"`
	UserID    sql.NullInt32  `json:"user_id"`
	ProjectID sql.NullInt32  `json:"project_id"`
	Date      sql.NullTime   `json:"date"`
	Text      sql.NullString `json:"text"`
}

type User struct {
	ID          int32          `json:"id"`
	Email       string         `json:"email"`
	Password    string         `json:"password"`
	Firstname   sql.NullString `json:"firstname"`
	Surname     sql.NullString `json:"surname"`
	MobilePhone sql.NullString `json:"mobile_phone"`
}
