// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	DeleteAssignedProjectByID(ctx context.Context, projectID int32) error
	DeleteProjectByID(ctx context.Context, id int32) error
	DeleteProjectCommentByID(ctx context.Context, id int32) error
	DeleteUserByID(ctx context.Context, id int32) error
	GetAssignedProjectByID(ctx context.Context, projectID int32) (Assignedproject, error)
	GetAssignedProjects(ctx context.Context) ([]Assignedproject, error)
	GetProjectByID(ctx context.Context, id int32) (Project, error)
	GetProjectCommentByID(ctx context.Context, id int32) (Projectcomment, error)
	GetProjectCommentsByProjectID(ctx context.Context, projectID int32) ([]Projectcomment, error)
	GetProjects(ctx context.Context) ([]Project, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	GetUsers(ctx context.Context) ([]User, error)
	InsertAssignedProject(ctx context.Context, arg InsertAssignedProjectParams) (int32, error)
	InsertProject(ctx context.Context, arg InsertProjectParams) (int32, error)
	InsertProjectComment(ctx context.Context, arg InsertProjectCommentParams) (int32, error)
	InsertUser(ctx context.Context, arg InsertUserParams) (int32, error)
	UpdateAssignedProjectByID(ctx context.Context, arg UpdateAssignedProjectByIDParams) (int32, error)
	UpdateProjectByID(ctx context.Context, arg UpdateProjectByIDParams) (int32, error)
	UpdateProjectCommentByID(ctx context.Context, arg UpdateProjectCommentByIDParams) (int32, error)
	UpdateUserByID(ctx context.Context, arg UpdateUserByIDParams) (int32, error)
}

var _ Querier = (*Queries)(nil)
